- hosts: all
  tasks:
    - name: Install packages
      ansible.builtin.include_role:
        name: packages
    - name: Change Ubuntu settings
      ansible.builtin.include_role:
        name: ubuntu
